<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="EPPlus" Version="7.2.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Coordinates\Coordinates.csproj" />
    <ProjectReference Include="..\LoggingConnector\LoggingConnector.csproj" />
  </ItemGroup>
</Project>